ponte01:
  build: .
  expose:
   - "3000"
   - "1883"
  links:
   - mongodb

ponte02:
  build: .
  expose:
   - "3000"
   - "1883"
  links:
   - mongodb

mongodb:
  image: mongo

haproxy:
  image: haproxy
  volumes:
   - haproxy:/usr/local/etc/haproxy
  links:
   - ponte01
   - ponte02
  ports:
   - "80:80"
   - "1883:1883"
   - "3000:3000"
  expose:
   - "80"
   - "1883"
   - "3000"
